### ISSUE TITLE
Deprecate manage_stock in core

### ISSUE THREAD

**Issue by kloon** [woocommerce/woocommerce-product-tables-feature-plugin#100]
The manage_stock field is not part of the new schema, instead we rely on a combination of stock_status and stock_quantity to determine of stock should be managed.

Deprecate the manage_stock functionality from core and then later remove it.

**Comment by kloon** [comment]
Closed via https://github.com/woocommerce/woocommerce/commit/2d9c05887645964b94b46ef2376a66403a4e4504

**Comment by kloon** [comment]
Reopening, speaking to Mike we are holding off on this until merged into core.

**Comment by mikejolley** [comment]
manage_stock is still a useful getter - I think we should keep this around. How the data store handles this is not relevant.
