### ISSUE TITLE
Core: Deprecated `wc_get_product_variation_attributes` and remove direct post meta handling

### ISSUE THREAD

**Issue by kloon** [woocommerce/woocommerce-product-tables-feature-plugin#102]
Deprecate wc_get_product_variation_attributes in favour of read_attributes.

Searching the source for `wc_get_product_variation_attributes` reveals lots of direct post meta usage we need to refactor, e.g. in the AJAX handlers.

**Comment by kloon** [comment]
Reopening, speaking to Mike we are holding off on this until merged into core.

**Comment by mikejolley** [comment]
Updated the description for this - looks like core needs some work.

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce-product-tables-feature-plugin/issues/107
