### ISSUE TITLE
Filter by product type in admin is empty

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce-product-tables-feature-plugin#105]
This filter outputs terms. There are none with custom tables.

**Comment by kloon** [comment]
Not able to recreate this, entries show in the dropdown for me, believe there are still terms that ties into wp_posts entries?

**Comment by mikejolley** [comment]
Clean install, import dummy content, see dropdown.

For me, empty...terms were empty.

**Comment by mikejolley** [comment]
Unable to replicate now. Closing.
