### ISSUE TITLE
PHP Warning

### ISSUE THREAD

**Issue by robin-scott** [woocommerce/woocommerce-product-tables-feature-plugin#114]
Giving this a whirl on some large databases to test, and seeing some PHP warnings (PHP 7.2) coming out:

Warning: Invalid argument supplied for foreach() in /wp-content/plugins/woocommerce-product-tables-feature-plugin-1.0-beta-1/includes/class-wc-product-tables-migrate-data.php on line 397

Opening issue here to resolve.

**Comment by robin-scott** [comment]
Line 397 in this release is:

`foreach ( $default_attributes as $default_attr ) {`

Also getting similar warning for line 427 which is also:

`foreach ( $default_attributes as $default_attr ) {`

I think the issue will be related to the lack of default attributes in here.

Also seeing this for line 85, which is a different, but similar:

`foreach ( $downloadable_files as $download_key => $downloadable_file ) {`

It may be related to client data here, but warning is not so verbose. Looks like we are running a for each which does not apply (or should not apply) in this migration process.

**Comment by robin-scott** [comment]
I need to test this on another dataset to narrow this down, and will also get a look through the relevant file here and adjust it to get this data migrating correctly. BTW this is a large products db with a lot of variable products in it, sent to test all the edge and corner cases :)

**Comment by kloon** [comment]
Downloads one has been fixed in #112 Will fix the attributes one as well now.

**Comment by robin-scott** [comment]
Too fast for me... I was raising this to close it here :)
