### ISSUE TITLE
Using DOUBLE as storage type is not recommended, use DECIMAL instead

### ISSUE THREAD

**Issue by javorszky** [woocommerce/woocommerce-product-tables-feature-plugin#117]
From the MySQL documentation: https://dev.mysql.com/doc/refman/5.6/en/problems-with-float.html

> [...] the difference between the numbers shows up around the tenth decimal or so, depending on factors such as computer architecture or the compiler version or optimization level. For example, different CPUs may evaluate floating-point numbers differently.

Similarly on MariaDB: https://mariadb.com/kb/en/library/floating-point-accuracy/

> f1, f2 and f3 have seemingly identical values across each row, but due to floating point accuracy, the results may be unexpected.
> ```
> CREATE TABLE fpn (id INT, f1 FLOAT, f2 DOUBLE, f3 DECIMAL (10,3));
> INSERT INTO fpn VALUES (1,2,2,2),(2,0.1,0.1,0.1);
> 
> SELECT * FROM fpn WHERE f1*f1 = f2*f2;
> +------+------+------+-------+
> | id   | f1   | f2   | f3    |
> +------+------+------+-------+
> |    1 |    2 |    2 | 2.000 |
> +------+------+------+-------+
> ```
> The reason why only one instead of two rows was returned becomes clear when we see how the floating point squares were evaluated.
> ```
> SELECT f1*f1, f2*f2, f3*f3 FROM fpn;
> +----------------------+----------------------+----------+
> | f1*f1                | f2*f2                | f3*f3    |
> +----------------------+----------------------+----------+
> |                    4 |                    4 | 4.000000 |
> | 0.010000000298023226 | 0.010000000000000002 | 0.010000 |
> +----------------------+----------------------+----------+

`FLOAT` and `DOUBLE` on both MariaDB and MySQL are approximate values and are stored differently internally as how the values are given to the database. Comparison with equality would yield unexpected results, for example "Grab me all products that cost 10.00".

`DECIMAL` and `NUMERIC` on the other hand are exact values, so comparing them is safer.

**Comment by javorszky** [comment]
I suggest using `DECIMAL(20,4)` instead of `DOUBLE`.

PR incoming

**Comment by claudiosanches** [comment]
Thank you for reporting this issue!

I'm closing the issue as it already has a PR, please continue the discussion over at #118.
