### ISSUE TITLE
Error creating table wp_wc_products

### ISSUE THREAD

**Issue by fredrikborggren** [woocommerce/woocommerce-product-tables-feature-plugin#122]
Hello,

When defining keys for table wp_wc_products there needs to be backticks around table column "virtual", maybe virtual is a restricted name or such?

In file "class-wc-product-tables-install.php" at row "56":

```KEY `virtual` (`virtual`),```

Best
Fredrik

**Comment by kloon** [comment]
This was fixed in https://github.com/woocommerce/woocommerce-product-tables-feature-plugin/commit/e791d366b4db5093e28711c0dacc503108718ab6
