### ISSUE TITLE
[Question] Will you guys preserve the WP Exporter functionality?

### ISSUE THREAD

**Issue by redlagoon** [woocommerce/woocommerce-product-tables-feature-plugin#123]
The new tables are looking great, but will you guys preserve the hooks on the WP exporter and work with the new data to make sure it all works?

The reason why this is **critical**  is compatibility with XML. As of now, the WP Export / Import knows how to deal with xml files but if you guys decide to make a new export / import, you'd have to provide us with functionality that we can call to do all of this.

Just trying to think ahead for a pretty common functionality.

Thank you.

**Comment by kloon** [comment]
@redlagoon yes, everything should stay backward compatible, even with all the default WP hooks.

**Comment by redlagoon** [comment]
@kloon Thank you a bunchton!
