### ISSUE TITLE
Can't migration ❌

### ISSUE THREAD

**Issue by guytzhak** [woocommerce/woocommerce-product-tables-feature-plugin#125]
I used the cli command: 'wp wc-product-tables migrate-data'

and the output error:
[Unknown table &#039;hilit.whlp_wc_products&#039;]<br /><code>DROP TABLE whlp_wc_products, whlp_wc_product_downloads, whlp_wc_product_attributes, whlp_wc_product_relationships, whlp_wc_product_attribute_values, whlp_wc_product_variation_attribute_values<
......
[You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near &#039;virtual (virtual),

**Comment by guytzhak** [comment]
The whole error from WP Error.log:

> 09-Oct-2018 12:43:58 UTC] WordPress database error You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'virtual (virtual),
> 			  KEY downloadable (downloadable),
> 			  KEY stock_status (' at line 26 for query 
> 			CREATE TABLE whlp_wc_products (
> 			  `product_id` bigint(20) NOT NULL,
> 			  `sku` varchar(100) NULL default '',
> 			  `image_id` bigint(20) NULL default 0,
> 			  `height` double NULL default NULL,
> 			  `width` double NULL default NULL,
> 			  `length` double NULL default NULL,
> 			  `weight` double NULL default NULL,
> 			  `stock_quantity` double NULL default NULL,
> 			  `type` varchar(100) NULL default 'simple',
> 			  `virtual` tinyint(1) NULL default 0,
> 			  `downloadable` tinyint(1) NULL default 0,
> 			  `tax_class` varchar(100) NULL default '',
> 			  `tax_status` varchar(100) NULL default 'taxable',
> 			  `total_sales` double NULL default 0,
> 			  `price` double NULL default NULL,
> 			  `regular_price` double NULL default NULL,
> 			  `sale_price` double NULL default NULL,
> 			  `date_on_sale_from` datetime NULL default NULL,
> 			  `date_on_sale_to` datetime NULL default NULL,
> 			  `average_rating` float NULL default 0,
> 			  `stock_status` varchar(100) NULL default 'instock',
> 			  PRIMARY KEY  (`product_id`),
> 			  KEY image_id (image_id),
> 			  KEY type (type),
> 			  KEY virtual (virtual),
> 			  KEY downloadable (downloadable),
> 			  KEY stock_status (stock_status)
> 
> 			) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci made by require('wp-admin/plugins.php'), activate_plugin, do_action('activate_woocommerce-product-tables-feature-plugin-1.0-beta-1/woocommerce-product-tables-feature-plugin.php'), WP_Hook->do_action, WP_Hook->apply_filters, wc_custom_product_tables_activate, WC_Product_Tables_Install::activate, dbDelta
> [09-Oct-2018 12:43:59 UTC] WordPress database error Table 'hilit.whlp_wc_products' doesn't exist for query SELECT  DISTINCT whlp_posts.*, IF (whlp_posts.post_type = 'tribe_events', whlp_postmeta.meta_value, whlp_posts.post_date) AS post_date FROM whlp_posts  LEFT JOIN whlp_postmeta as whlp_postmeta on whlp_posts.ID = whlp_postmeta.post_id AND whlp_postmeta.meta_key = '_EventStartDateUTC' LEFT JOIN whlp_wc_products wc_products ON whlp_posts.ID = wc_products.product_id  WHERE 1=1  AND whlp_posts.post_name = 'events' AND whlp_posts.post_parent = 0  AND whlp_posts.post_type IN ('post', 'page', 'attachment', 'business', 'product', 'tribe_events') AND ((whlp_posts.post_status = 'publish' OR whlp_posts.post_status = 'inherit' OR whlp_posts.post_status = 'private'))  ORDER BY post_date DESC  made by require('wp-admin/plugins.php'), require_once('wp-admin/admin-header.php'), do_action('admin_notices'), WP_Hook->do_action, WP_Hook->apply_filters, Tribe__Admin__Notices->__call, Tribe__Events__Main->render_notice_archive_slug_conflict, WP_Query->__construct, WP_Query->query, WP_Query->get_posts
>

**Comment by rodrigoprimo** [comment]
Thanks for your report. PR #126 should address the issue in the first comment. It adds an `IF EXISTS` check to the query that drops the plugin tables. So, in the rare case that they don't exist, the query won't throw an error anymore.

I believe the second error is happening because `virtual` is a reserved word since MySQL 5.7.6 (https://dev.mysql.com/doc/refman/5.7/en/keywords.html#keywords-5-7-detailed-V). I wouldn't expect this to be an issue as we are quoting this word when creating the table (https://github.com/woocommerce/woocommerce-product-tables-feature-plugin/blob/master/includes/class-wc-product-tables-install.php#L56). So I'm not sure why this error is happening and we will need to further investigate.

**Comment by seldimi** [comment]
Just change KEY to 
KEY virtual (`virtual`),

**Comment by rodrigoprimo** [comment]
@seldimi, I'm not sure if I follow your suggestion. We are escaping it already, aren't we?

https://github.com/woocommerce/woocommerce-product-tables-feature-plugin/blob/master/includes/class-wc-product-tables-install.php#L56

**Comment by seldimi** [comment]
If you download it from here, its not escaped "Source cdoe (zip)"
https://github.com/woocommerce/woocommerce-product-tables-feature-plugin/releases

**Comment by mikejolley** [comment]
Download master; thats an older release.
