### ISSUE TITLE
wc_get_products only getting products in custom table?

### ISSUE THREAD

**Issue by erikdemarco** [woocommerce/woocommerce-product-tables-feature-plugin#145]
```
$args = array(
'limit' => 9999,
);
$results = wc_get_products( $args );
```

above code will only return products that created when 'woocommerce-product-tables' activated. is that normal? isn't it supposed to fetch all products using old table as well?

I'm using the most up to date woocommerce version.

**Comment by claudiosanches** [comment]
This plugin will make `wc_get_products()` only get data from the new table, so it's normal, also in order for this plugin fully work, will require migrate all data. We currently are working on improving the data migration.
