### ISSUE TITLE
Woo 3.6.1 Compatibility?

### ISSUE THREAD

**Issue by directnetstores** [woocommerce/woocommerce-product-tables-feature-plugin#146]
Just tried this plugin for the first time. None of the product images appear. I can't find any settings for this plugin either. Doe it have any? 

Or maybe it's just not compatible with the recent BIG update to Woo 3.6
??

**Comment by claudiosanches** [comment]
> Or maybe it's just not compatible with the recent BIG update to Woo 3.6

It's compatible with 3.6.

> Just tried this plugin for the first time. None of the product images appear. I can't find any settings for this plugin either. Doe it have any?

There's no settings, and sounds like didn't migrate all data, that's why missing product images.
