### ISSUE TITLE
Will this ever be merged into Woocommerce ?

### ISSUE THREAD

**Issue by miculgigant** [woocommerce/woocommerce-product-tables-feature-plugin#161]
Not really an issue, but this project was said to be merged into WooCommerce at the beginning of 2019 and it's the end of 2019 and still nothing. I feel this is an important development for WooCommerce, so what's the holdback ?

**Comment by claudiosanches** [comment]
This maybe never will get merged into WooCommerce, we are working on it and checking it will really improve performance for most of the stores, still this isn't the only solution, we are also working in another solutions like lookup tables (included in WooCommerce 3.6 last year).
I understand that the intent of this project creates certainly hopes in everyone, but this doesn't mean this will solve all performance issues, depending on the plugins you use maybe will not have any improvement.
