### ISSUE TITLE
WC_USE_TRANSACTIONS already defined

### ISSUE THREAD

**Issue by rodrigoprimo** [woocommerce/woocommerce-product-tables-feature-plugin#65]
I'm getting the following PHP notice when running WC core tests from this plugin repository:

```
Notice: Constant WC_USE_TRANSACTIONS already defined in wp-content/plugins/woocommerce/tests/bootstrap.php on line 67
```

WC_USE_TRANSACTIONS was added to https://github.com/woocommerce/woocommerce-product-tables-feature-plugin/blob/master/tests/class-wcpt-unit-tests-bootstrap.php in commit 575aee9c6a4f02d4b77532ac07c5bb6e71a31d75:

https://github.com/woocommerce/woocommerce-product-tables-feature-plugin/blob/575aee9c6a4f02d4b77532ac07c5bb6e71a31d75/tests/class-wcpt-unit-tests-bootstrap.php#L37

We can probably remove it from `tests/class-wcpt-unit-tests-bootstrap.php` since WC core already defines it with the same value:

https://github.com/woocommerce/woocommerce/blob/0c10c28cd3b22908a161f4fc13103a96444cd3cd/tests/bootstrap.php#L67

cc @mikejolley as you added the constant. Let me know if I'm missing something. Maybe in some cases, the constant is not defined by WC core and then, instead of removing it from the custom product tables plugin, we should add a check to if it is already defined?

**Comment by mikejolley** [comment]
@rodrigoprimo If core unit tests define it, you can drop. It was added to prevent unit tests breaking due to transactions which conflict with transactions in the WP core unit test suite.
