### ISSUE TITLE
Method Case mismatch

### ISSUE THREAD

**Issue by kmg-yrabelo** [woocommerce/woocommerce-product-tables-feature-plugin#73]
Hey guys,

Taking a quick look at the code and spotted this. Method name should be `get_id()` instead of `get_Id()`

https://github.com/woocommerce/woocommerce-product-tables-feature-plugin/blob/89a4cfcd94c2e6bb663d18b49330c631571f3ab1/includes/data-stores/class-wc-product-variable-data-store-custom-table.php#L507

**Comment by claudiosanches** [comment]
Closed in favor of #74
Thanks.
