### ISSUE TITLE
Undefined variable in WC_Product_Tables_Backwards_Compatibility::set_variation_description()

### ISSUE THREAD

**Issue by rodrigoprimo** [woocommerce/woocommerce-product-tables-feature-plugin#84]
Commit f2ca5ff7c8c9aa623c71b6cd2de3321009832011 added the following line to WC_Product_Tables_Backwards_Compatibility::set_variation_description():

https://github.com/woocommerce/woocommerce-product-tables-feature-plugin/blob/40f8f962da5a630cd3a26f9c38b55cca941f34b4/includes/class-wc-product-tables-backwards-compatibility.php#L420

The problem is that `$post_ID` is not defined. Since this code is called if `post_content` for all product variations is updated, instead of calling `clean_post_cache()` passing a single product ID, I imagine we should call `wp_cache_flush()` or some other more specific function to clean the cache for all product variations instead of cleaning the cache of just a single product variation.

Can you take a look, @claudiosanches?

**Comment by claudiosanches** [comment]
See #86
