### ISSUE TITLE
Adapt getter and setter methods to return null in core

### ISSUE THREAD

**Issue by kloon** [woocommerce/woocommerce-product-tables-feature-plugin#99]
This is probably a WooCommerce core change, but we need to adapt the getter and setter methods in core to return null for certain fields as we allow null values for these.

height
length
width
weight
stock_quantity 
price
regular_price
sale_price
date_on_sale_from
date_on_sale_to
average_rating

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce-product-tables-feature-plugin/issues/106
